version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: default
      POSTGRES_DB: logistics
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
